"""replace google_credentials with google_linked

Revision ID: 5d6b49770e4b
Revises: 333def97f030
Create Date: 2025-11-04 11:57:14.927376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6b49770e4b'
down_revision: Union[str, None] = '333def97f030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_linked', sa.Boolean(), nullable=True))
    op.drop_column('users', 'google_credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_credentials', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'google_linked')
    # ### end Alembic commands ###
