"""add_goal_columns

Revision ID: 61889f7d92cf
Revises: 
Create Date: 2025-10-21 19:00:55.380691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61889f7d92cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('goals', sa.Column('study_schedule', sa.String(length=50), nullable=True))
    op.add_column('goals', sa.Column('weekly_hours', sa.String(length=10), nullable=True))
    op.add_column('goals', sa.Column('learning_style', sa.String(length=50), nullable=True))
    op.add_column('goals', sa.Column('weekly_schedule', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('resources', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('milestones', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('completed', sa.Boolean(), nullable=True))
    op.alter_column('goals', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('goals', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('goals', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('goals', 'completed')
    op.drop_column('goals', 'milestones')
    op.drop_column('goals', 'resources')
    op.drop_column('goals', 'weekly_schedule')
    op.drop_column('goals', 'learning_style')
    op.drop_column('goals', 'weekly_hours')
    op.drop_column('goals', 'study_schedule')
    op.drop_column('goals', 'difficulty')
    # ### end Alembic commands ###
